services:
  mini-redis:
    build: .
    container_name: mini-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/app/storage
    restart: unless-stopped
    environment:
      - NODE_ENV=production

volumes:
  redis-data:
